version: 2

project_name: chatwork-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: cw
    main: ./cmd/cw
    binary: cw
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X github.com/kokoichi206/chatwork-cli/internal/version.Version={{ .Version }}
      - -X github.com/kokoichi206/chatwork-cli/internal/version.Commit={{ .Commit }}
      - -X github.com/kokoichi206/chatwork-cli/internal/version.Date={{ .Date }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native
